Task 11
TreshMom/formal-lang-course pull request #13
Opened 2024-05-29 20:49 UTC by TreshMom

Здравствуйте!

2024-05-29 21:04 UTC, TreshMom commented
Я удалил тесты, потому что после ваших обновлений к 9 дз, 3 так перестал проходить и 9 дз я не доделал еще.
Время подходила к дедлайну и чтобы быстро поправить все оставил только 11 тесты.

2024-05-30 09:26 UTC, WoWaster requested changes
Я запомню, что у вас сдано вовремя, но пока не почините этот треш с тестами, не зачту.

2024-06-11 16:26 UTC, TreshMom commented
Разрешил все проблемы связанные с тестами, локально все проходит, я hw 9 там тоже открыл, если есть возможность гляньте пожалуйста)

2024-06-12 10:45 UTC, WoWaster requested changes
Избавьтесь от сгенерированных файлов ANTLR и будет счастье

2024-06-25 12:39 UTC, TreshMom commented
Смотрите на commit test, все тесты должны пройти, локально все ок было.
У последнего коммита отменил test, чтобы по несколько раз не гонять (на момент отмены все тесты passed были), он нужен был для слияния с другой веткой, для дз.

2024-06-25 16:54 UTC, WoWaster approved these changes

2024-06-25 20:07 UTC, closed without merging