Task 6
TreshMom/formal-lang-course pull request #9
Opened 2024-04-10 17:15 UTC by TreshMom

Диффы по 3/4 таксу и 6 тут, пока в 6 16 тестов из 66 не проходят

2024-04-10 20:06 UTC, TreshMom commented
Сделал!

2024-04-11 13:59 UTC, WoWaster requested changes
Вы же поправили 4 задачку. Подтяните её сюда, чтобы не удалять файлик с тестами...

2024-04-11 13:59 UTC, WoWaster commented on tests/autotests/test_task4.py
Кхм, ну не надо удалять наши файлики :(

2024-04-17 19:26 UTC, TreshMom commented
С точки зрения тестов - все ок. Я залил 4 таск и возник конфликт, я его разрешил, но только вот забыл про pre-commit и black) 
Теперь все ок.

2024-04-17 19:33 UTC, TreshMom commented
первый фулл балл за дз, это победа.
Но в диффах снова какой-то треш...

2024-04-18 11:06 UTC, WoWaster approved these changes
Я сделаю вид, что весь этот треш я не наблюдаю и смотрю только на тестики...

2024-04-18 12:14 UTC, merged